{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kybers-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kybers-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
